// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llm.baseUrl": string;
      "llm.apiKey": string;
      "llm.model": string;
      "llm.temperature": string;
      "research.direction": string;
      "research.criteria": string;
      "feeds.list": string;
      "fetch.daysLimit": number;
      "fetch.workers": number;
      "collection.name": string;
      "tags.research": string;
      "autoRun.enable": boolean;
      "autoRun.intervalHours": number;
      "autoRun.lastRun": number;
    };
  }
}
