// Paper Radar default preferences.
// Scaffold binds these to `extensions.zotero.paperRadar.*` at build time.

// LLM backend: OpenAI-compatible triple (baseUrl + model + apiKey).
// Default is Volcano Ark Coding Plan; any OpenAI-compatible endpoint works.
// baseUrl is everything before "/chat/completions"; the full request URL is
// resolved automatically at runtime (see src/modules/config.ts).
pref("llm.baseUrl", "https://ark.cn-beijing.volces.com/api/coding/v3");
pref("llm.apiKey", "");
pref("llm.model", "deepseek-v4-flash");
// LLM sampling temperature, stored as string (Zotero pref numbers are
// 32-bit integers and cannot hold floats).
pref("llm.temperature", "0.2");

// Research direction: free-form description of the user's research field.
pref(
  "research.direction",
  "基于数据的桥梁承载能力评估与损伤识别、中小跨径桥梁（空心板梁桥、T梁桥、小箱梁桥、斜交桥等多梁体系）、横向分布系数、影响线/影响面。",
);

// Evaluation criteria prompt. Can be regenerated by the "AI 生成评估要求"
// button from the research direction above.
// NOTE: the first-line output format rule (【相关度：高/中/低】) is required
// by the review parser and must not be removed.
pref(
  "research.criteria",
  "【评估要求】：\n1. 第一行必须且只能严格按格式输出：【相关度：高】 或 【相关度：中】 或 【相关度：低】。\n   - 【高】：直接研究基于数据的桥梁承载能力评估、多梁体系（空心板/T梁/小箱梁/斜交）、横向分布系数、影响线/影响面。\n   - 【中】：研究方法可借鉴（如基于挠度/应变的模型更新、通用梁桥损伤识别、结构健康监测数据分析；未明确指明具体桥型但属于通用梁桥评估/分析的）。\n   - 【低】：非桥梁领域、大型缆索桥梁（斜拉/悬索桥）、单纯材料学研究等无关方向。\n2. 请用 2 句简明扼要的中文总结该文的研究内容与核心方法。",
);

// RSS feeds, one URL per line.
pref(
  "feeds.list",
  "https://apps.wanfangdata.com.cn/perios/rss/gclx\nhttps://apps.wanfangdata.com.cn/perios/rss/gljtkj\nhttps://apps.wanfangdata.com.cn/perios/rss/gwql\nhttps://apps.wanfangdata.com.cn/perios/rss/tmgcxb\nhttps://apps.wanfangdata.com.cn/perios/rss/zdycj\nhttps://apps.wanfangdata.com.cn/perios/rss/zgglxb\nhttps://apps.wanfangdata.com.cn/perios/rss/zgtdkx\nhttps://ascelibrary.org/action/showFeed?type=etoc&feed=rss&jc=jbenf2\nhttps://ascelibrary.org/action/showFeed?type=etoc&feed=rss&jc=jsendh\nhttps://rss.sciencedirect.com/publication/science/01410296\nhttps://rss.sciencedirect.com/publication/science/23520124\nhttps://rss.sciencedirect.com/publication/science/02638231\nhttps://rss.sciencedirect.com/publication/science/0022460X\nhttps://www.tandfonline.com/feed/rss/nsie20",
);

// Fetch behavior.
pref("fetch.daysLimit", 9);
pref("fetch.workers", 6);

// Output.
pref("collection.name", "AI精选前沿论文");
pref("tags.research", "承载能力评估");

// Auto run.
pref("autoRun.enable", false);
pref("autoRun.intervalHours", 168);
pref("autoRun.lastRun", 0);
